services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: intermittent-web:dev
    container_name: intermittent-web-dev
    environment:
      TERM:
      COLORTERM:
    volumes:
      - .:/workspace
      - ~/work/intermittent-importers:/rails
      - node-modules:/workspace/node_modules
      - home-node:/home/node
    network_mode: host
    security_opt:
      - no-new-privileges:true
    stdin_open: true
    tty: true
volumes:
  node-modules:
  home-node:
