import type { FastifyReply, FastifyRequest } from "fastify";
import { querySmall } from "./lib/db.js";
import { calculateInterval, getAreaContext, buildDualAxisOptions, type DashboardParams } from "./electricityMix.js";
import { buildChartOptions, getProductionTypeIds, getProductionTypeOptions } from "./sharedCharts.js";

type Query = { width?: string; min_interval?: string; production_type?: string; units?: string; nuclear_multiplier?: string; wind_multiplier?: string; solar_multiplier?: string; demand_multiplier?: string };
type Row = Record<string, any>;

async function resolveUnitIds(areaIds: number[], q: Query) {
  if (q.units && q.units !== 'all') return q.units.split(',').map(Number).filter(Boolean);
  if (q.production_type && q.production_type !== 'all') {
    const rows = await querySmall<{id:number}>(`SELECT u.id FROM units u INNER JOIN production_types pt ON u.production_type_id=pt.id WHERE pt.name = ANY($1::text[]) AND u.area_id = ANY($2::int[])`, [q.production_type.split(','), areaIds]); return rows.map(r=>r.id);
  }
  return (await querySmall<{id:number}>(`SELECT id FROM units WHERE area_id = ANY($1::int[]) LIMIT 200`, [areaIds])).map(r=>r.id);
}
async function unitMeta(areaIds:number[]){ const production_types=await getProductionTypeOptions(areaIds); const units=await querySmall<Row>(`SELECT u.id,COALESCE(u.name,u.internal_id) AS name,u.internal_id,pt.name AS production_type,a.code AS area FROM units u INNER JOIN production_types pt ON u.production_type_id=pt.id INNER JOIN areas a ON u.area_id=a.id WHERE u.area_id=ANY($1::int[]) ORDER BY pt.name,a.code,u.name`,[areaIds]); return {production_types,units};}

const movingCapSql = `WITH cap AS (SELECT unit_id,LAST(value,time) AS value FROM generation_unit_capacities WHERE time BETWEEN $1 AND $2 AND unit_id=ANY($3::int[]) GROUP BY unit_id), g AS (SELECT time_bucket_gapfill('1h', time) AS time, unit_id, COALESCE(AVG(value),0) AS value FROM generation_unit WHERE time BETWEEN $1 AND $2 AND unit_id=ANY($3::int[]) GROUP BY 1,2) SELECT EXTRACT(EPOCH FROM time_bucket($4::interval,time) AT TIME ZONE $5)*1000 AS time, CONCAT_WS(' - ',u.internal_id,u.name) AS metric, AVG(AVG(g.value)) OVER w / NULLIF(AVG(cap.value),0) AS moving_capacity FROM g INNER JOIN cap USING(unit_id) INNER JOIN units u ON(unit_id=u.id) WHERE time BETWEEN $1 AND $2 GROUP BY unit_id,time_bucket($4::interval,time),2 WINDOW w AS (PARTITION BY unit_id ORDER BY time_bucket($4::interval,time) RANGE '12 month' PRECEDING) ORDER BY 2,1`;
const movingOutputSql = `SELECT EXTRACT(EPOCH FROM time AT TIME ZONE $5)*1000 AS time, metric, value FROM (SELECT time_bucket_gapfill($1::interval,time) AS time, CONCAT_WS(' - ',u.internal_id,u.name,'output') AS metric, AVG(value) AS value FROM generation_unit g INNER JOIN units u ON(unit_id=u.id) WHERE time BETWEEN $2 AND $3 AND unit_id=ANY($4::int[]) GROUP BY 1,u.internal_id,u.name ORDER BY 2,1) s`;
export async function perUnitMovingCapacity(req:FastifyRequest<{Params:DashboardParams;Querystring:Query}>,reply:FastifyReply){const ctx=await getAreaContext(req.params); const unitIds=await resolveUnitIds(ctx.areaIds,req.query); const interval=calculateInterval(ctx.from,ctx.to,req.query.width,req.query.min_interval); const from12=new Date(ctx.from); from12.setMonth(from12.getMonth()-12); const cap=await querySmall<Row>(movingCapSql,[from12,ctx.to,unitIds,`${interval} seconds`,ctx.timezone]); const out=await querySmall<Row>(movingOutputSql,[`${interval} seconds`,ctx.from,ctx.to,unitIds,ctx.timezone]); const series=[...capSeries(cap),...outputSeries(out)]; return reply.send({options:buildDualAxisOptions(series,'Per Unit Moving Capacity Factor & Output'),height:567,timezone:ctx.timezoneAbbreviation,...await unitMeta(ctx.areaIds)});}
function capSeries(rows:Row[]){const m=new Map<string,any>(); for(const r of rows){const k=String(r.metric); if(!m.has(k))m.set(k,{name:`${k} (capacity %)`,type:'line',unit:'percent',symbol:'none',lineStyle:{width:2},data:[]}); m.get(k).data.push([Number(r.time),r.moving_capacity==null?null:Number(r.moving_capacity)]);} return [...m.values()];}
function outputSeries(rows:Row[]){const m=new Map<string,any>(); for(const r of rows){const k=String(r.metric); if(!m.has(k))m.set(k,{name:k,type:'line',unit:'power',symbol:'none',lineStyle:{width:2,type:'dashed'},yAxisIndex:1,data:[]}); m.get(k).data.push([Number(r.time),r.value==null?null:Number(r.value)*1000]);} return [...m.values()];}

const captureSql = `WITH _hourly AS (SELECT time_bucket('1h',time) AS time, areas_production_type_id, AVG(g.value) AS value FROM generation_data g WHERE time BETWEEN $1 AND $2 AND areas_production_type_id IN(SELECT id FROM areas_production_types WHERE area_id=ANY($3::int[]) AND production_type_id=ANY($4::int[])) GROUP BY 1,2), _agg AS (SELECT time_bucket($5::interval,time) AS time, a.code||'/'||pt.name AS name, SUM(g.value) AS total_kwh, SUM(NULLIF(g.value,0)*p.value)/NULLIF(SUM(g.value),0)/100 AS capture_price, SUM(NULLIF(g.value,0)*p.value)/NULLIF(SUM(g.value),0)/NULLIF(AVG(p.value),0) AS capture_rate FROM _hourly g INNER JOIN areas_production_types apt ON(areas_production_type_id=apt.id) INNER JOIN areas a ON(area_id=a.id) INNER JOIN production_types pt ON(production_type_id=pt.id) INNER JOIN prices p USING(area_id,time) WHERE time BETWEEN $1 AND $2 GROUP BY 1,2) SELECT EXTRACT(EPOCH FROM time AT TIME ZONE $6)*1000 AS time,name,capture_price,capture_rate FROM _agg WHERE total_kwh IS NOT NULL AND total_kwh<>0 ORDER BY 2,1`;
export async function capturePrice(req:FastifyRequest<{Params:DashboardParams;Querystring:Query}>,reply:FastifyReply){const ctx=await getAreaContext(req.params); const interval=calculateInterval(ctx.from,ctx.to,req.query.width,req.query.min_interval); const pt=await getProductionTypeIds(ctx.areaIds,req.query.production_type); const rows=await querySmall<Row>(captureSql,[ctx.from,ctx.to,ctx.areaIds,pt,`${interval} seconds`,ctx.timezone]); const series=[...simpleSeries(rows,'capture_price','price',1),...simpleSeries(rows,'capture_rate','percent',1,' (rate)',1)]; return reply.send({options:buildDualAxisOptions(series,'Capture Prices'),height:900,timezone:ctx.timezoneAbbreviation,production_types:await getProductionTypeOptions(ctx.areaIds)});}
function simpleSeries(rows:Row[],field:string,unit:string,mul=1,suffix='',axis=0){const m=new Map<string,any>(); for(const r of rows){const k=String(r.name)+suffix; if(!m.has(k))m.set(k,{name:k,type:'line',unit,symbol:'none',lineStyle:{width:2},yAxisIndex:axis,data:[]}); m.get(k).data.push([Number(r.time),r[field]==null?null:Number(r[field])*mul]);} return [...m.values()];}

const mapSql = `WITH _gen AS (SELECT time_bucket_gapfill('1h',time) AS time, area_id, production_type_id, INTERPOLATE(AVG(value)) AS value FROM generation g INNER JOIN areas a ON(area_id=a.id) WHERE area_id=ANY($1::int[]) AND electricitymaps_id IS NOT NULL AND production_type_id=ANY($2::int[]) AND time BETWEEN $3 AND $4 GROUP BY 1,2,3), _gen_sum AS (SELECT time,area_id,SUM(value) AS value FROM _gen GROUP BY 1,2), _peak AS (SELECT area_id,production_type_id,MAX(value) AS value FROM generation g INNER JOIN areas a ON(area_id=a.id) WHERE area_id=ANY($1::int[]) AND electricitymaps_id IS NOT NULL AND production_type_id=ANY($2::int[]) AND time BETWEEN ($3::timestamptz - '1 year'::interval) AND $4::timestamptz GROUP BY 1,2), _peak_sum AS (SELECT area_id,SUM(value) AS value FROM _peak GROUP BY 1) SELECT EXTRACT(EPOCH FROM time AT TIME ZONE $5)*1000 AS time, a.electricitymaps_id AS metric, g.value/NULLIF(peak.value,0) AS value FROM _gen_sum g INNER JOIN _peak_sum peak ON(g.area_id=peak.area_id) INNER JOIN areas a ON(g.area_id=a.id) WHERE time BETWEEN $3 AND $4 ORDER BY 1`;
export async function maps(req:FastifyRequest<{Params:DashboardParams;Querystring:Query}>,reply:FastifyReply){const ctx=await getAreaContext(req.params); const pt=await getProductionTypeIds(ctx.areaIds,req.query.production_type||'nuclear'); const areas=(await querySmall<{id:number}>(`SELECT id FROM areas WHERE region=ANY($1::text[]) AND enabled='t' AND code <> ALL($2::text[])`,[['europe','mexico','brazil','canada','south_africa','usa','india'],['BR-N','BR-NE','BR-S','NEVP']])).map(r=>r.id); const rows=await querySmall<Row>(mapSql,[areas,pt,ctx.from,ctx.to,ctx.timezone]); const frames=buildFrames(rows); return reply.send({frames,options:mapOptions(frames),geoJsonUrl:'/assets/world-rewound.geojson',height:800,timezone:ctx.timezoneAbbreviation});}
function buildFrames(rows:Row[]){const map=new Map<number,any>(); for(const r of rows){const t=Number(r.time); if(!map.has(t))map.set(t,{data:[{locations:[],z:[]}],layout:{title:new Date(t).toLocaleString()},name:String(t)}); map.get(t).data[0].locations.push(r.metric); map.get(t).data[0].z.push(Number(r.value));} return [...map.values()];}
function mapOptions(frames:any[]){const build=(f:any)=>(f?.data?.[0]?.locations||[]).map((loc:string,i:number)=>({name:loc,value:f.data[0].z[i]})); return {baseOption:{timeline:{axisType:'category',autoPlay:true,playInterval:500,data:frames.map((f,i)=>({value:i,text:f.layout.title})),left:'10%',right:'10%',bottom:20},title:{text:'',left:'center',top:10},tooltip:{trigger:'item',formatter:'{b}: ({c}%)'},visualMap:{min:0,max:1,left:'left',top:'bottom',text:['High','Low'],calculable:true},series:[{name:'Value',type:'map',map:'world',roam:true,nameProperty:'zoneName',data:build(frames[0])}],animation:false},options:frames.map(f=>({title:{text:f.layout.title},series:[{data:build(f)}]}))};}

export async function simulations(req:FastifyRequest<{Params:DashboardParams;Querystring:Query}>,reply:FastifyReply){
  const ctx=await getAreaContext(req.params); const interval=calculateInterval(ctx.from,ctx.to,req.query.width,req.query.min_interval); const pt=await getProductionTypeIds(ctx.areaIds,req.query.production_type); const mult={nuclear:Number(req.query.nuclear_multiplier||1),wind:Number(req.query.wind_multiplier||1),solar:Number(req.query.solar_multiplier||1),demand:Number(req.query.demand_multiplier||1)};
  const genSql=`SELECT EXTRACT(EPOCH FROM time AT TIME ZONE $5)*1000 AS time, CASE WHEN SUM(value)<0 THEN name2||'_negative' ELSE name2 END AS metric, SUM(value) AS value FROM (SELECT time_bucket_gapfill($1::interval,time) AS time, pt.name, pt.name2, INTERPOLATE(CASE WHEN pt.name='nuclear' THEN AVG(g.value)*$6 WHEN pt.name LIKE 'wind%' THEN AVG(g.value)*$7 WHEN pt.name LIKE 'solar%' THEN AVG(g.value)*$8 ELSE AVG(g.value) END) AS value FROM generation_data g INNER JOIN areas_production_types apt ON(g.areas_production_type_id=apt.id) INNER JOIN production_types pt ON(apt.production_type_id=pt.id) WHERE time BETWEEN $2 AND $3 AND apt.area_id=ANY($4::int[]) AND apt.production_type_id=ANY($9::int[]) GROUP BY 1,pt.name,pt.name2) s GROUP BY 1,name2 ORDER BY 2,1`;
  const demandSql=`SELECT EXTRACT(EPOCH FROM time AT TIME ZONE $5)*1000 AS time, 'demand' AS metric, SUM(value)*$6 AS value FROM (SELECT time_bucket_gapfill($1::interval,time) AS time, INTERPOLATE(AVG(l.value)) AS value FROM load l WHERE time BETWEEN $2 AND $3 AND area_id=ANY($4::int[]) GROUP BY 1 UNION SELECT time_bucket_gapfill($1::interval,time) AS time, INTERPOLATE(AVG(g.value)) AS value FROM generation_data g INNER JOIN areas_production_types apt ON(g.areas_production_type_id=apt.id) INNER JOIN production_types pt ON(apt.production_type_id=pt.id) INNER JOIN areas a ON(apt.area_id=a.id) WHERE time BETWEEN $2 AND $3 AND apt.area_id=ANY($4::int[]) AND pt.name='solar_rooftop' AND a.source='aemo' GROUP BY 1) s GROUP BY 1 ORDER BY 1`;
  const transSql=`SELECT EXTRACT(EPOCH FROM time AT TIME ZONE $5)*1000 AS time, CASE WHEN SUM(value)<0 THEN 'export' ELSE 'import' END AS metric, SUM(value) AS value FROM ((SELECT time_bucket_gapfill($1::interval,time) AS time, from_area_id, to_area_id, INTERPOLATE(AVG(t.value)) AS value FROM transmission_data t INNER JOIN areas_areas aa ON(t.areas_area_id=aa.id) WHERE aa.from_area_id=ANY($4::int[]) AND NOT (aa.to_area_id=ANY($4::int[])) AND time BETWEEN $2 AND $3 GROUP BY 1,2,3) UNION (SELECT time_bucket_gapfill($1::interval,time) AS time, to_area_id AS from_area_id, from_area_id AS to_area_id, INTERPOLATE(-AVG(t.value)) AS value FROM transmission_data t INNER JOIN areas_areas aa ON(t.areas_area_id=aa.id) WHERE aa.to_area_id=ANY($4::int[]) AND NOT (aa.from_area_id=ANY($4::int[])) AND time BETWEEN $2 AND $3 GROUP BY 1,2,3)) s INNER JOIN areas from_area ON(from_area_id=from_area.id) INNER JOIN areas to_area ON(to_area_id=to_area.id) WHERE (from_area.type <> 'country' OR to_area.type='country') GROUP BY 1 ORDER BY 1`;
  const args=[`${interval} seconds`,ctx.from,ctx.to,ctx.areaIds,ctx.timezone];
  const gen=await querySmall<Row>(genSql,[...args,mult.nuclear,mult.wind,mult.solar,pt]);
  const demand=await querySmall<Row>(demandSql,[...args,mult.demand]);
  const trans=await querySmall<Row>(transSql,args);
  const options=simulationOptions(gen,demand,trans);
  return reply.send({options,height:900,timezone:ctx.timezoneAbbreviation,production_types:await getProductionTypeOptions(ctx.areaIds)});
}

function simSeries(rows:Row[]){const m=new Map<string,any>(); for(const r of rows){const k=String(r.metric); if(!m.has(k))m.set(k,{name:k,type:'line',unit:'power',stack:k.endsWith('_negative')?'negative':'total',symbol:'none',areaStyle:{opacity:.75},lineStyle:{width:0},data:[]}); m.get(k).data.push([Number(r.time),r.value==null?null:Number(r.value)*1000]);} return [...m.values()];}

function simulationOptions(genRows:Row[], demandRows:Row[], transRows:Row[]) {
  const genSeries=simSeries(genRows).map(s=>({...s,xAxisIndex:0,yAxisIndex:0}));
  const demandSeries=simSeries(demandRows).map(s=>({...s,name:'demand',stack:undefined,areaStyle:undefined,lineStyle:{width:2},itemStyle:{color:'rgb(36, 41, 46)'},xAxisIndex:0,yAxisIndex:0}));
  const transSeries=simSeries(transRows).map(s=>({...s,xAxisIndex:0,yAxisIndex:0,itemStyle:{color:'rgb(163, 82, 204)'}}));
  const byTime=new Map<number,{gen:number,load:number,trans:number}>();
  for(const r of genRows){const t=Number(r.time); const o=byTime.get(t)||{gen:0,load:0,trans:0}; o.gen+=Number(r.value||0); byTime.set(t,o)}
  for(const r of demandRows){const t=Number(r.time); const o=byTime.get(t)||{gen:0,load:0,trans:0}; o.load+=Number(r.value||0); byTime.set(t,o)}
  for(const r of transRows){const t=Number(r.time); const o=byTime.get(t)||{gen:0,load:0,trans:0}; o.trans+=Number(r.value||0); byTime.set(t,o)}
  let cumSurplus=0,cumDeficit=0,cumMatched=0,sumDeficit=0; const diff:any[]=[], genLine:any[]=[], loadLine:any[]=[], transLine:any[]=[], sumDefData:any[]=[], matched:any[]=[], surplus:any[]=[], deficit:any[]=[];
  for(const [t,o] of [...byTime.entries()].sort((a,b)=>a[0]-b[0])){const d=o.gen+o.trans-o.load; cumSurplus+=Math.max(0,d); cumDeficit+=Math.min(0,d); cumMatched+=Math.min(o.gen+o.trans,o.load); sumDeficit=Math.min(0,sumDeficit+d); genLine.push([t,o.gen*1000]); loadLine.push([t,o.load*1000]); transLine.push([t,o.trans*1000]); diff.push([t,d*1000]); sumDefData.push([t,sumDeficit*1000]); matched.push([t,cumMatched*1000]); surplus.push([t,cumSurplus*1000]); deficit.push([t,cumDeficit*1000]);}
  return {height:900,title:[{text:'Generation',left:'center',right:'15%',top:10},{text:'Summary',left:'93.5%',top:10,textAlign:'center'},{text:'Cumulative Deficit',left:'center',right:'15%',top:'36%'},{text:'Difference',left:'center',top:'65%'}],tooltip:{trigger:'axis',formatter:{type:'multi'}},legend:[{type:'scroll',top:30,left:'center',right:'15%',data:[...new Set([...genSeries,...demandSeries,...transSeries].map(s=>s.name))]},{top:'60%',left:'93%',data:['Surplus','Matched','Deficit']},{top:'38%',left:'center',right:'15%',data:['sum deficit']},{top:'67%',left:'center',data:['transmission','generation','load','diff','sum deficit','cum matched','cum surplus','cum deficit']}],grid:[{left:'3%',right:'15%',top:'10%',height:'25%'},{left:'89%',right:'2%',top:'10%',height:'48%'},{left:'3%',right:'15%',top:'40%',height:'25%'},{left:'3%',right:'2%',top:'69%',height:'26%'}],xAxis:[{type:'time',gridIndex:0,axisLabel:{show:false}},{type:'category',gridIndex:1,data:['']},{type:'time',gridIndex:2,axisLabel:{show:false}},{type:'time',gridIndex:3}],yAxis:[{type:'value',gridIndex:0,axisLabel:{formatter:{type:'power'}}},{type:'value',gridIndex:1,axisLabel:{formatter:{type:'energy'}}},{type:'value',gridIndex:2,axisLabel:{formatter:{type:'energy'}}},{type:'value',gridIndex:3,axisLabel:{formatter:{type:'power'}}}],series:[...transSeries,...genSeries,...demandSeries,{name:'Matched',type:'bar',unit:'energy',xAxisIndex:1,yAxisIndex:1,stack:'total',itemStyle:{color:'rgb(86, 166, 75)'},data:[cumMatched*1000]},{name:'Surplus',type:'bar',unit:'energy',xAxisIndex:1,yAxisIndex:1,stack:'total',itemStyle:{color:'rgb(242, 204, 12)'},data:[cumSurplus*1000]},{name:'Deficit',type:'bar',unit:'energy',xAxisIndex:1,yAxisIndex:1,stack:'total',itemStyle:{color:'rgb(224, 47, 68)'},data:[cumDeficit*1000]},{name:'sum deficit',type:'line',unit:'energy',xAxisIndex:2,yAxisIndex:2,symbol:'none',data:sumDefData},{name:'transmission',type:'line',unit:'power',xAxisIndex:3,yAxisIndex:3,symbol:'none',data:transLine},{name:'generation',type:'line',unit:'power',xAxisIndex:3,yAxisIndex:3,symbol:'none',data:genLine},{name:'load',type:'line',unit:'power',xAxisIndex:3,yAxisIndex:3,symbol:'none',data:loadLine},{name:'diff',type:'line',unit:'power',xAxisIndex:3,yAxisIndex:3,symbol:'none',data:diff},{name:'cum matched',type:'line',unit:'energy',xAxisIndex:3,yAxisIndex:3,symbol:'none',data:matched},{name:'cum surplus',type:'line',unit:'energy',xAxisIndex:3,yAxisIndex:3,symbol:'none',data:surplus},{name:'cum deficit',type:'line',unit:'energy',xAxisIndex:3,yAxisIndex:3,symbol:'none',data:deficit}]};
}

export async function sweden(req:FastifyRequest<{Params:DashboardParams;Querystring:Query}>,reply:FastifyReply){
  const ctx=await getAreaContext({...req.params, region:'europe', area_type:'region', area:'SE1,SE2,SE3,SE4'});
  const interval=calculateInterval(ctx.from,ctx.to,req.query.width,req.query.min_interval);
  const sql=`SELECT EXTRACT(EPOCH FROM time AT TIME ZONE $5)*1000 AS time, metric, SUM(value) AS value FROM (SELECT time_bucket_gapfill($1::interval,time) AS time, a.code||'/load' AS metric, INTERPOLATE(AVG(l.value)) AS value FROM load l INNER JOIN areas a ON(l.area_id=a.id) WHERE time BETWEEN $2 AND $3 AND area_id=ANY($4::int[]) GROUP BY 1,2 UNION SELECT time_bucket_gapfill($1::interval,time) AS time, a.code||'/'||pt.name AS metric, INTERPOLATE(AVG(g.value)) AS value FROM generation g INNER JOIN areas a ON(g.area_id=a.id) INNER JOIN production_types pt ON(g.production_type_id=pt.id) WHERE time BETWEEN $2 AND $3 AND area_id=ANY($4::int[]) GROUP BY 1,2) s GROUP BY 1,metric ORDER BY 2,1`;
  const rows=await querySmall<Row>(sql,[`${interval} seconds`,ctx.from,ctx.to,ctx.areaIds,ctx.timezone]);
  return reply.send({options:buildChartOptions(simSeries(rows),'Sweden','power'),height:768,timezone:ctx.timezoneAbbreviation});
}
